services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: blog-api-app
    container_name: blog-api
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - blog-api-network

  db:
    image: mysql:8.0
    container_name: blog-api-db
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - blog-api-network

  nginx:
    image: nginx:stable-alpine
    container_name: blog-api-nginx
    ports:
      - 8080:80
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - blog-api-network

networks:
  blog-api-network:
    driver: bridge

volumes:
  mysql_data:
