version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: blog-api:latest
    container_name: blog-api
    restart: always
    ports:
      - "9000:9000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=blog_api
      - DB_USERNAME=root
      - DB_PASSWORD=root
    volumes:
      - .:/var/www
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: blog-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: blog_api
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    container_name: blog-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  db_data:
